version: '3.8'

services:
  mysql:
      container_name: mysql
      image: mysql:5
      volumes:
        - ./database:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: agenda-petshop
      ports:
        - "3306:3306"
